pod 'Intercom'
pod 'MagicalRecord/Shorthand'
pod 'NSDate+TimeAgo'
pod 'ObjectiveSugar', :git => 'https://github.com/supermarin/ObjectiveSugar'
pod 'SAMTextField'
pod 'MTMigration'
pod 'HPReorderTableView', :git => 'https://github.com/hpique/HPReorderTableView'
pod 'ReactiveCocoa'
pod 'Mantle'
pod 'SZTextView'