pod 'Intercom'
pod 'MagicalRecord/Shorthand'
pod 'NSDate+TimeAgo'
pod 'RSDayFlow'
pod 'ObjectiveSugar'
pod 'SAMTextField'
pod 'MTMigration'
pod 'HPReorderTableView', :git => 'https://github.com/hpique/HPReorderTableView'
pod 'MCSwipeTableViewCell'